services:
  - type: web
    name: gear-glitch-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd frontend && rm -rf node_modules .next && NODE_ENV= npm install && cd .. && rm -rf node_modules dist && NODE_ENV= npm install && npx tsc
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8020
      - key: BASE_URL
        value: https://gears-glitch.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true
